name: example
description: A new Flutter project.

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_avatar:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/asian-boy-avatar.png
