name: easy_avatar
description: A plug-in that provides solutions to avatar-related problems in Flutter applications.
auth:
  name: Jcak Lee
  email: 291148484@163.com
  home: http://thispage.tech

maintainer: Jcak Lee
homepage: https://github.com/jacklee1995
repository: https://github.com/jacklee1995/flutter_easy_avatar
issue_tracker: https://github.com/jacklee1995/flutter_easy_avatar/issues
version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
