name: easy_avatar
description: A plug-in that provides solutions to avatar-related problems in Flutter applications.
auth:
  name: Jcak Lee
  email: 291148484@163.com
  home: http://thispage.tech

maintainer: Jcak Lee
homepage: http://thispage.tech:9680/jclee1995/flutter-easy-avatar.git
repository: https://github.com/jacklee1995/flutter_easy_avatar.git
issue_tracker: https://github.com/jacklee1995/flutter_easy_avatar/issues
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
